version: "3.3"

services:
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - "3035:3035"
  fake_payment_provider:
    build:
      context: .
      dockerfile: ./fake_payment_provider/Dockerfile
    ports:
      - "5055:5055"
  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
  products:
    build:
      context: .
      dockerfile: ./products/Dockerfile
  orders:
    build:
      context: .
      dockerfile: ./orders/Dockerfile
  cart:
    build:
      context: .
      dockerfile: ./cart/Dockerfile
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - gateway
