version: "3.3"

services:
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - "3035:3035"
    restart: on-failure
  payment_provider:
    build:
      context: .
      dockerfile: ./payment_provider/Dockerfile
    ports:
      - "5055:5055"
    restart: on-failure
  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    restart: on-failure
  products:
    build:
      context: .
      dockerfile: ./products/Dockerfile
    restart: on-failure
  orders:
    build:
      context: .
      dockerfile: ./orders/Dockerfile
    restart: on-failure
  cart:
    build:
      context: .
      dockerfile: ./cart/Dockerfile
    restart: on-failure
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:80"
  hook:
    build:
      context: .
      dockerfile: ./hook/Dockerfile
    ports:
      - "4035:4035"
    restart: on-failure
  redis:
    image: redis:alpine3.13
  database:
    image: mongo:4.2.16
    restart: always
    volumes:
      - "database_data:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - "ME_CONFIG_MONGODB_URL=mongodb://database:27017/"
      - "ME_CONFIG_MONGODB_ADMINUSERNAME="
      - "ME_CONFIG_MONGODB_ADMINPASSWORD="
volumes:
  database_data:
