name: Build auth image and push docker hub
on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout code
        run: |
          docker login -p ${{ secrets.DOCKER_PASSWORD }} -u ${{ secrets.DOCKER_USERNAME }}
          docker build -t yigitsadic/fake_store_auth -f auth/Dockerfile .
          docker push yigitsadic/fake_store_auth:latest
