// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cart struct {
	Items      []*CartItem `json:"items"`
	ItemsCount int         `json:"itemsCount"`
}

type CartItem struct {
	ID          string  `json:"id"`
	ProductID   string  `json:"productId"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Image       string  `json:"image"`
}

type LoginResponse struct {
	ID       string `json:"id"`
	Avatar   string `json:"avatar"`
	FullName string `json:"fullName"`
	Token    string `json:"token"`
}

type Order struct {
	PaymentAmount float64    `json:"paymentAmount"`
	CreatedAt     string     `json:"createdAt"`
	OrderItems    []*Product `json:"orderItems"`
}

type Product struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Image       string  `json:"image"`
}
