// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginResponse struct {
	ID       string `json:"id"`
	Avatar   string `json:"avatar"`
	FullName string `json:"fullName"`
	Token    string `json:"token"`
}
