// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: favourites.proto

package favourites_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product_ProductStatus int32

const (
	Product__         Product_ProductStatus = 0
	Product_CREATED   Product_ProductStatus = 1
	Product_POPULATED Product_ProductStatus = 2
)

// Enum value maps for Product_ProductStatus.
var (
	Product_ProductStatus_name = map[int32]string{
		0: "_",
		1: "CREATED",
		2: "POPULATED",
	}
	Product_ProductStatus_value = map[string]int32{
		"_":         0,
		"CREATED":   1,
		"POPULATED": 2,
	}
)

func (x Product_ProductStatus) Enum() *Product_ProductStatus {
	p := new(Product_ProductStatus)
	*p = x
	return p
}

func (x Product_ProductStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Product_ProductStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_favourites_proto_enumTypes[0].Descriptor()
}

func (Product_ProductStatus) Type() protoreflect.EnumType {
	return &file_favourites_proto_enumTypes[0]
}

func (x Product_ProductStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Product_ProductStatus.Descriptor instead.
func (Product_ProductStatus) EnumDescriptor() ([]byte, []int) {
	return file_favourites_proto_rawDescGZIP(), []int{1, 0}
}

type ListFavouritesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *ListFavouritesRequest) Reset() {
	*x = ListFavouritesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favourites_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFavouritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavouritesRequest) ProtoMessage() {}

func (x *ListFavouritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_favourites_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavouritesRequest.ProtoReflect.Descriptor instead.
func (*ListFavouritesRequest) Descriptor() ([]byte, []int) {
	return file_favourites_proto_rawDescGZIP(), []int{0}
}

func (x *ListFavouritesRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductID string                `protobuf:"bytes,2,opt,name=productID,proto3" json:"productID,omitempty"`
	UserID    string                `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	Status    Product_ProductStatus `protobuf:"varint,4,opt,name=status,proto3,enum=favourites.Product_ProductStatus" json:"status,omitempty"`
	Title     string                `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Image     string                `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *Product) Reset() {
	*x = Product{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favourites_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_favourites_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_favourites_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

func (x *Product) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *Product) GetStatus() Product_ProductStatus {
	if x != nil {
		return x.Status
	}
	return Product__
}

func (x *Product) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Product) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type ListFavouritesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Products []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *ListFavouritesResponse) Reset() {
	*x = ListFavouritesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favourites_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFavouritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavouritesResponse) ProtoMessage() {}

func (x *ListFavouritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_favourites_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavouritesResponse.ProtoReflect.Descriptor instead.
func (*ListFavouritesResponse) Descriptor() ([]byte, []int) {
	return file_favourites_proto_rawDescGZIP(), []int{2}
}

func (x *ListFavouritesResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type FavouritesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductID string `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	UserID    string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *FavouritesRequest) Reset() {
	*x = FavouritesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favourites_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavouritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavouritesRequest) ProtoMessage() {}

func (x *FavouritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_favourites_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavouritesRequest.ProtoReflect.Descriptor instead.
func (*FavouritesRequest) Descriptor() ([]byte, []int) {
	return file_favourites_proto_rawDescGZIP(), []int{3}
}

func (x *FavouritesRequest) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

func (x *FavouritesRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type FavouritesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *FavouritesResponse) Reset() {
	*x = FavouritesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favourites_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavouritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavouritesResponse) ProtoMessage() {}

func (x *FavouritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_favourites_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavouritesResponse.ProtoReflect.Descriptor instead.
func (*FavouritesResponse) Descriptor() ([]byte, []int) {
	return file_favourites_proto_rawDescGZIP(), []int{4}
}

func (x *FavouritesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ProductInFavouritesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InFavourites bool `protobuf:"varint,1,opt,name=inFavourites,proto3" json:"inFavourites,omitempty"`
}

func (x *ProductInFavouritesResponse) Reset() {
	*x = ProductInFavouritesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_favourites_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductInFavouritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInFavouritesResponse) ProtoMessage() {}

func (x *ProductInFavouritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_favourites_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInFavouritesResponse.ProtoReflect.Descriptor instead.
func (*ProductInFavouritesResponse) Descriptor() ([]byte, []int) {
	return file_favourites_proto_rawDescGZIP(), []int{5}
}

func (x *ProductInFavouritesResponse) GetInFavourites() bool {
	if x != nil {
		return x.InFavourites
	}
	return false
}

var File_favourites_proto protoreflect.FileDescriptor

var file_favourites_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x66, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x22, 0x2f,
	0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22,
	0xea, 0x01, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x39, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x21, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x32, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x05, 0x0a, 0x01, 0x5f, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a,
	0x09, 0x50, 0x4f, 0x50, 0x55, 0x4c, 0x41, 0x54, 0x45, 0x44, 0x10, 0x02, 0x22, 0x49, 0x0a, 0x16,
	0x4c, 0x69, 0x73, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x75,
	0x72, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x22, 0x49, 0x0a, 0x11, 0x46, 0x61, 0x76, 0x6f, 0x75,
	0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x22, 0x2e, 0x0a, 0x12, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x22, 0x41, 0x0a, 0x1b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6e, 0x46,
	0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x6e, 0x46, 0x61, 0x76, 0x6f, 0x75,
	0x72, 0x69, 0x74, 0x65, 0x73, 0x32, 0xf4, 0x02, 0x0a, 0x11, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72,
	0x69, 0x74, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x0e, 0x4c,
	0x69, 0x73, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x12, 0x21, 0x2e,
	0x66, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46,
	0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0d, 0x4d, 0x61, 0x72, 0x6b, 0x46, 0x61,
	0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x75, 0x72,
	0x69, 0x74, 0x65, 0x73, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69,
	0x74, 0x65, 0x73, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0f, 0x55, 0x6e, 0x4d, 0x61,
	0x72, 0x6b, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x66, 0x61,
	0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x66, 0x61, 0x76,
	0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x12,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6e, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69,
	0x74, 0x65, 0x12, 0x1d, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x2e,
	0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x27, 0x2e, 0x66, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x2e, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6e, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f,
	0x66, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x66, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_favourites_proto_rawDescOnce sync.Once
	file_favourites_proto_rawDescData = file_favourites_proto_rawDesc
)

func file_favourites_proto_rawDescGZIP() []byte {
	file_favourites_proto_rawDescOnce.Do(func() {
		file_favourites_proto_rawDescData = protoimpl.X.CompressGZIP(file_favourites_proto_rawDescData)
	})
	return file_favourites_proto_rawDescData
}

var file_favourites_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_favourites_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_favourites_proto_goTypes = []interface{}{
	(Product_ProductStatus)(0),          // 0: favourites.Product.ProductStatus
	(*ListFavouritesRequest)(nil),       // 1: favourites.ListFavouritesRequest
	(*Product)(nil),                     // 2: favourites.Product
	(*ListFavouritesResponse)(nil),      // 3: favourites.ListFavouritesResponse
	(*FavouritesRequest)(nil),           // 4: favourites.FavouritesRequest
	(*FavouritesResponse)(nil),          // 5: favourites.FavouritesResponse
	(*ProductInFavouritesResponse)(nil), // 6: favourites.ProductInFavouritesResponse
}
var file_favourites_proto_depIdxs = []int32{
	0, // 0: favourites.Product.status:type_name -> favourites.Product.ProductStatus
	2, // 1: favourites.ListFavouritesResponse.products:type_name -> favourites.Product
	1, // 2: favourites.FavouritesService.ListFavourites:input_type -> favourites.ListFavouritesRequest
	4, // 3: favourites.FavouritesService.MarkFavourite:input_type -> favourites.FavouritesRequest
	4, // 4: favourites.FavouritesService.UnMarkFavourite:input_type -> favourites.FavouritesRequest
	4, // 5: favourites.FavouritesService.ProductInFavourite:input_type -> favourites.FavouritesRequest
	3, // 6: favourites.FavouritesService.ListFavourites:output_type -> favourites.ListFavouritesResponse
	5, // 7: favourites.FavouritesService.MarkFavourite:output_type -> favourites.FavouritesResponse
	5, // 8: favourites.FavouritesService.UnMarkFavourite:output_type -> favourites.FavouritesResponse
	6, // 9: favourites.FavouritesService.ProductInFavourite:output_type -> favourites.ProductInFavouritesResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_favourites_proto_init() }
func file_favourites_proto_init() {
	if File_favourites_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_favourites_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFavouritesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favourites_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Product); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favourites_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFavouritesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favourites_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavouritesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favourites_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavouritesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_favourites_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductInFavouritesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_favourites_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_favourites_proto_goTypes,
		DependencyIndexes: file_favourites_proto_depIdxs,
		EnumInfos:         file_favourites_proto_enumTypes,
		MessageInfos:      file_favourites_proto_msgTypes,
	}.Build()
	File_favourites_proto = out.File
	file_favourites_proto_rawDesc = nil
	file_favourites_proto_goTypes = nil
	file_favourites_proto_depIdxs = nil
}
