name: Build client image and push docker hub
on:
  push:
    branches:
      - master
    paths:
      - 'client/**'

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout code
        run: |
          docker login -p ${{ secrets.DOCKER_PASSWORD }} -u ${{ secrets.DOCKER_USERNAME }}
          docker build -t yigitsadic/fake_store_client -f client/Dockerfile --build-arg TARGET_API_URL="http://161.35.75.56:3035/query" .
          docker push yigitsadic/fake_store_client:latest
